version: "3"
services:
  postgres:
    #image: postgres
    build: ./postgres
    hostname: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  dspace:
    build: .
    ports:
      - 80:8080
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB_HOST=postgres
      - POSTGRES_ADMIN_USER=postgres
      - POSTGRES_ADMIN_PASSWORD=postgres
      - POSTGRES_SCHEMA=dspace
      - POSTGRES_USER=dspace
      - POSTGRES_PASSWORD=password
    volumes:
      - ./dspace/app/dspace-6.3-src-release:/tmp/dspace
      - ./cache/.m2:/root/.m2
#      - ./cache/dspace_home:/dspace
    command: start-dspace

volumes:
  db_data:
