version: "3"
services:
  postgres:
    build: ./postgres
    hostname: postgres
    #restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database_backups:/dspace/database_backups
    ports:
      - 127.0.0.1:5432:5432

volumes:
  db_data:
