version: "3"
services:
  postgres:
    #image: postgres
    build: ./postgres
    hostname: postgres
    #restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  dspace:
#    image: dspace-63_dspace:latest
    build: .
    ports:
      - 80:8080
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB_HOST=postgres
      - POSTGRES_ADMIN_USER=postgres
      - POSTGRES_ADMIN_PASSWORD=postgres
      - POSTGRES_SCHEMA=dspace
      - POSTGRES_USER=dspace
      - POSTGRES_PASSWORD=password

    command: start-dspace

volumes:
  db_data:
