version: "2.2"
services:
  postgres:
    #image: postgres
    build: ./postgres
    hostname: postgres
    #restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database_backups:/dspace/database_backups

  dspace:
#    image: dspace-63_dspace:latest
    build: .
#    ports:
#      - 80:8080
    expose:
      - 8080
    networks:
      - default
      - arqgeo
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB_HOST=postgres
      - POSTGRES_ADMIN_USER=postgres
      - POSTGRES_ADMIN_PASSWORD=postgres
      - POSTGRES_SCHEMA=dspace
      - POSTGRES_USER=dspace
      - POSTGRES_PASSWORD=password
      - EMAIL_USER=arqgeo@ict.ufvjm.edu.br
      - EMAIL_PASSWORD=ermjit6cYNeDZ1QGDyggWW71ZaXnDI
    volumes:
      - ./assetstore:/dspace/assetstore

    command: start-dspace

volumes:
  db_data:

networks:
  arqgeo:
   name: "arqgeo"
